language: php

php:
  - 7.4

os: linux

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - cp .env.testing .env
  - php artisan key:generate
  - php artisan migrate

before_install:
  - mysql -e 'CREATE DATABASE privbin;'

script:
  - php artisan test

services:
  - mysql

notifications:
  email: false
